import MenuIcon from "@mui/icons-material/Menu";
import usepLogo from "../assets/images/logo/usep_logo.png";
import CustomIcon from "../components/common/CustomIcon";
import HomeOutlinedIcon from "@mui/icons-material/HomeOutlined";
import StickyNote2OutlinedIcon from "@mui/icons-material/StickyNote2Outlined";
import LogoutOutlinedIcon from "@mui/icons-material/LogoutOutlined";
import WarningAmberOutlinedIcon from "@mui/icons-material/WarningAmberOutlined";
import SchemaOutlinedIcon from "@mui/icons-material/SchemaOutlined";
import RecommendOutlinedIcon from "@mui/icons-material/RecommendOutlined";
import SettingsOutlinedIcon from "@mui/icons-material/SettingsOutlined";
import DeleteIcon from "@mui/icons-material/Delete";
import DownloadIcon from "@mui/icons-material/Download";
import FolderIcon from "@mui/icons-material/Folder";
import VisibilityIcon from "@mui/icons-material/Visibility";
import EditIcon from "@mui/icons-material/Edit";
import MoreVertIcon from "@mui/icons-material/MoreVert";
import FilterListIcon from "@mui/icons-material/FilterList";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import HighlightOffIcon from "@mui/icons-material/HighlightOff";
import ListAltIcon from "@mui/icons-material/ListAlt";
import NoteAltIcon from "@mui/icons-material/NoteAlt";
import { SxProps } from "@mui/material";

export const IconHome = ({ sx }: { sx?: SxProps }) => <HomeOutlinedIcon sx={{ ...sx }} />;
export const IconReport = ({ sx }: { sx?: SxProps }) => <StickyNote2OutlinedIcon sx={{ ...sx }} />;
export const IconLogout = ({ sx }: { sx?: SxProps }) => <LogoutOutlinedIcon sx={{ ...sx }} />;
export const IconWarning = ({ sx }: { sx?: SxProps }) => <WarningAmberOutlinedIcon sx={{ ...sx }} />;
export const IconDataScheme = ({ sx }: { sx?: SxProps }) => <SchemaOutlinedIcon sx={{ ...sx }} />;
export const IconRecommendation = ({ sx }: { sx?: SxProps }) => <RecommendOutlinedIcon sx={{ ...sx }} />;
export const IconSettings = ({ sx }: { sx?: SxProps }) => <SettingsOutlinedIcon sx={{ ...sx }} />;
export const IconDelete = ({ sx }: { sx?: SxProps }) => <DeleteIcon sx={{ ...sx }} />;
export const IconDownload = ({ sx }: { sx?: SxProps }) => <DownloadIcon sx={{ ...sx }} />;
export const IconEye = ({ sx }: { sx?: SxProps }) => <VisibilityIcon sx={{ ...sx }} />;
export const IconFolder = ({ sx }: { sx?: SxProps }) => <FolderIcon sx={{ ...sx }} />;
export const IconEdit = ({ sx }: { sx?: SxProps }) => <EditIcon sx={{ ...sx }} />;
export const IconHorizontalMore = ({ sx }: { sx?: SxProps }) => <MoreVertIcon sx={{ ...sx }} />;
export const IconFilter = ({ sx }: { sx?: SxProps }) => <FilterListIcon sx={{ ...sx }} />;
export const IconCircleCheck = ({ sx }: { sx?: SxProps }) => <CheckCircleOutlineIcon sx={{ ...sx }} />;
export const IconCircleCross = ({ sx }: { sx?: SxProps }) => <HighlightOffIcon sx={{ ...sx }} />;
export const IconListDocument = ({ sx }: { sx?: SxProps }) => <ListAltIcon sx={{ ...sx }} />;
export const IconEditNote = ({ sx }: { sx?: SxProps }) => <NoteAltIcon sx={{ ...sx }} />;
export const IconMenu = ({ sx }: { sx?: SxProps }) => <MenuIcon sx={{ ...sx }} />;

export const UsepLogo = () => <CustomIcon img={usepLogo} />;
