export const websiteHeader = "Privacy Impact Assessment"
export const schoolName = "University of Southeastern Philippines"

export const sideBarHeaderTitle = "USeP Privacy Impact Assessment Tool"
export const sideBarSubHeaderTitle = "College of Information and Computing"

export const visit = "Visit"

export const disclaimerTitle = "Disclaimer"
export const disclaimerParagraphA1 = "This"
export const disclaimerLinkPia = "Privacy Impact Assessment"
export const disclaimerParagraphA2 = "(PIA) is an instrument for assessing the potential impacts on privacy of a process, information system, program, software module, device or other initiative which processes personal information and sensitive information in consultation with stakeholders, for taking actions as necessary to treat, mitigate and avoid privacy risk."
export const disclaimerParagraphB = "This PIA is more than a tool, it is a process that begins at the earliest possible stages of an initiative when there are still opportunities to influence its outcome and thereby ensure privacy by design. It is a process that continues until, and even after, the project has been deployed. Initiatives vary substantially in scale and impact."
export const disclaimerParagraphC = "This website will help you create a PIA following a step-by-step instructional process that will result in a PIA report that may include documentation about measures taken for risk treatment to be monitored and reviewed by the DPO (Data Protection Officer)."

export const processNameDescription = "Select the process name of this Privacy Impact Assessment"
export const processNameTitle = "Process Name"
export const processNameLabel = `${processNameTitle}: `

export const assessmentVersionName = "Assessment Version: "
export const assessmentVersion = "1.0.0"

export const processDescriptionTitle = "Process Description"
export const processDescription = "Describe the process and its context. Define and specify its intended goals. Complete the form below to provide a detailed description of the process."
export const processTitle = "Process"
export const dataSubjectName = "dataSubjects"
export const dataSubjectLabel = "Data Subject(s): "
export const dataSubjectHint = "These are the individuals from whom the data is collected."
export const formName = "formName"
export const formNameLabel = "Form Name: "
export const formNameHint = "This is the form used to collect personal data."
export const formFieldLabel = "Data Field: "
export const formFieldHint = "These are the fields filled by the data subject in the form."
export const dataPurposeName = "processingPurpose"
export const dataPurposeLabel = "Purpose for Processing: "
export const dataPurposeHint = "This is the purpose for collecting the data."
export const dataSecurityName = "securityMeasure"
export const dataSecurityLabel = "Security Measure: "
export const dataSecurityHint = "This is how the collected data is secured."
export const processNarrativeLabel = "Process Narrative: "
export const processNarrativeHint = "This is a concise description of the steps involved in how the data is collected."
export const processLevelAnalysisTitle = "Process-Level Analysis: Data Lifecycle"
export const processLevelAnalysisDescription = "Ensure each data collection method aligns with the Data Privacy Principles outlined in Republic Act No. 10173. Answer the questions below to confirm compliance."
export const dataCollectionTitle = "Data Collection"
export const dataSourceLabel = "Data Source: "
export const collectionMethodLabel = "Collection Method: "
export const timingOfCollectionLabel = "Timing of Collection: "
export const dataUseTitle = "Data Use"
export const dataUseQuestion1 = "Is the data used as is, or does it undergo further processing?"
export const dataUseQuestion2 = "Is there automated decision-making involved?"
export const dataDisclosureTitle = "Data Disclosure"
export const dataDisclosureQuestion1 = "Is the data transferred to third parties?"
export const dataDisclosureQuestion2 = "Who are the third-party recipients?"
export const dataDisclosureQuestion3 = "What is the purpose of the transfer to the third party?"
export const dataDisclosureQuestion4 = "Is the data transfer supported by a data sharing agreement or a data outsourcing agreement?"
export const dataDisclosureQuestion5 = "Is the personal data transferred outside of the Philippines? If so, where?"
export const dataStorageDisposalTitle = "Data Storage or Disposal"
export const dataStorageDisposalQuestion1 = "What is the retention period?"
export const dataStorageDisposalQuestion2 = "Where is the data stored/how is it stored?"
export const dataStorageDisposalQuestion3 = "Is personal data being destroyed?"
export const dataProcessNoteDescription = "Remember to check if all inputs are valid"

export const riskAssessmentTitle = "Risk Assessment"
export const riskAssessmentDescription = "In this form you will be using the risk level calculator you will simply input the Identified threat/vulnerability and choose what level of Impact and probability it has on the process."
export const riskAssessmentColumn1 = "Threat/Vulnerability"
export const riskAssessmentColumn2 = "Impact"
export const riskAssessmentColumn3 = "Probability"
export const riskAssessmentColumn4 = "Risk Rating"
export const riskRatingMapTitle = "Risk Rating Map"
export const riskRatingColumn1 = "Rating"
export const riskRatingColumn2 = "Types"
export const riskRatingDescriptionA = "For the purpose of this section, a risk refers to the potential of an incident to result in harm or danger to a data subject or organization. Risks are those that could lead to the unauthorized collection, use, disclosure or access to personal data. It includes risks that the confidentiality, integrity and availability of personal data will not be maintained, or the risk that processing will violate rights of data subjects or privacy principles (transparency, legitimacy and proportionality)."
export const riskRatingDescriptionB = "The first step in managing risks is to identify them, including threats and vulnerabilities, and by evaluating its impact and probability"

export const processDataFlowsTitle = "Process Data Flows"
export const processDataFlowDescription = "In this section you will submit the Process Data Flow as an image, created using a third-party software for making diagram and charts"
export const processDataFlowInstructionsA = visit
export const processDataFlowInstructionsB = "to start making the process data flow"
export const processDataFlowImgLabel = "File Input"
export const processDataColumnA = "Sample"
export const processDataColumnB = "Legend"

export const recommendedSolTitle = "Recommended Solutions"
export const recommendedSolDescription = "Identify the recommended solutions or mitigation measures, along with their corresponding priority numbers, and indicate the level of prioritization you believe they should receive."
export const recommendedSolInstruction = "In the same column, you have the option to cite the existing controls you've implemented to mitigate the risks."
export const recommendedSolColumnA = "Recommendation"
export const recommendedSolColumnB = "Priority No."

export const noteLabel = "Note: "
export const notApplicableNote = "Put N/A if not applicable"
export const tableColumnAction = "Action"
export const btnStart = "Start"
export const btnBack = "Back"
export const btnNext = "Next"
export const btnFinish = "Finish"
export const btnAddField = "Add field"
export const btnAdd = "Add"
export const btnRemoveField = "Remove field"
export const btnSave = "Save"
export const btnValidate = "Validate"
export const btnRemove = "Remove"
export const btnAddProcess = "Add Process"
export const btnCalculate = "Calculate"
export const btnToggleDescription = "Toggle Description"
export const btnToggleGuide = "Toggle Guide"
export const btnFileUpload = "Choose File"
export const btnSubmit = "Submit"
export const btnOrder = "Order"

export const linkDiagram = "diagrams.net"

