export const websiteHeader = "Privacy Impact Assessment"

export const schoolName = "University of Southeastern Philippines"

export const sideBarHeaderTitle = "USeP Privacy Impact Assessment Tool" 
export const sideBarSubHeaderTitle = "College of Information and Computing"

export const disclaimerTitle = "Disclaimer"
export const processNameDescription = "Select the process name of this Privacy Impact Assessment"
export const processNameLabel = "Process Name: "

export const assessmentVersionName = "Assessment Version: "
export const assessmentVersion = "1.0.0"
export const processDescriptionTitle = "Process Description"
export const processDescription = "Describe the process and its context. Define and specify its intended goals. Complete the form below to provide a detailed description of the process."
export const processTitle = "Process"
export const dataSubjectLabel = "Data Subject(s): "
export const dataSubjectHint = "These are the individuals from whom the data is collected."
export const formNameLabel = "Form Name: "
export const formNameHint = "This is the form used to collect personal data."
export const formFieldLabel = "Data Field: "
export const formFieldHint = "These are the fields filled by the data subject in the form."
export const dataPurposeLabel = "Purpose for Processing: "
export const dataPurposeHint = "This is the purpose for collecting the data."
export const dataSecurityLabel = "Security Measure: "
export const dataSecurityHint = "This is how the collected data is secured."
export const processNarrativeLabel = "Process Narrative: "
export const processNarrativeHint = "This is a concise description of the steps involved in how the data is collected."
export const processLevelAnalysisTitle = "Process-Level Analysis: Data Lifecycle"
export const processLevelAnalysisDescription = "Ensure each data collection method aligns with the Data Privacy Principles outlined in Republic Act No. 10173. Answer the questions below to confirm compliance."
export const dataCollectionTitle = "Data Collection"
export const dataSourceLabel = "Data Source: "
export const collectionMethodLabel = "Collection Method: "
export const timingOfCollectionLabel = "Timing of Collection: "
export const dataUseTitle = "Data Use"
export const dataUseQuestion1 = "Is the data used as is, or does it undergo further processing?"
export const dataUseQuestion2 = "Is there automated decision-making involved?"
export const dataDisclosureTitle = "Data Disclosure"
export const dataDisclosureQuestion1 = "Is the data transferred to third parties?"
export const dataDisclosureQuestion2 = "Who are the third-party recipients?"
export const dataDisclosureQuestion3 = "What is the purpose of the transfer to the third party?"
export const dataDisclosureQuestion4 = "Is the data transfer supported by a data sharing agreement or a data outsourcing agreement?"
export const dataDisclosureQuestion5 = "Is the personal data transferred outside of the Philippines? If so, where?"
export const dataStorageDisposalTitle = "Data Storage or Disposal"
export const dataStorageDisposalQuestion1 = "What is the retention period?"
export const dataStorageDisposalQuestion2 = "Where is the data stored/how is it stored?"
export const dataStorageDisposalQuestion3 = "Is personal data being destroyed?"

export const noteLabel = "Note: "
export const notApplicableNote = "Put N/A if not applicable"
export const btnStart = "Start"
export const btnBack = "Back"
export const btnNext = "Next"
export const btnAddField = "Add field"
export const btnRemoveField = "Remove field"
export const btnSave = "Save"
export const btnRemove = "Remove"
export const btnAddProcess = "Add Process"